import type { CompanyCatalogEntry } from "@/lib/stocks/types";

/** US large-cap catalog — swap for DB/API query at production scale */
export const CATALOG_ENTRIES: CompanyCatalogEntry[] = [
  { ticker: "GOOGL", name: "Alphabet Inc.", exchange: "NASDAQ", sector: "Technology", industry: "Internet Content", description: "Search, advertising, cloud, and AI platforms including Google and YouTube." },
  { ticker: "GOOG", name: "Alphabet Inc. Class C", exchange: "NASDAQ", sector: "Technology", industry: "Internet Content", description: "Class C shares of Alphabet Inc." },
  { ticker: "BRK.B", name: "Berkshire Hathaway Inc.", exchange: "NYSE", sector: "Financial Services", industry: "Conglomerate", description: "Diversified holding company with insurance, railroads, and investments." },
  { ticker: "LLY", name: "Eli Lilly and Company", exchange: "NYSE", sector: "Healthcare", industry: "Pharmaceuticals", description: "Develops and manufactures pharmaceutical products worldwide." },
  { ticker: "V", name: "Visa Inc.", exchange: "NYSE", sector: "Financial Services", industry: "Payment Processing", description: "Global payments technology company facilitating electronic transactions." },
  { ticker: "MA", name: "Mastercard Inc.", exchange: "NYSE", sector: "Financial Services", industry: "Payment Processing", description: "Technology company in the global payments industry." },
  { ticker: "UNH", name: "UnitedHealth Group Inc.", exchange: "NYSE", sector: "Healthcare", industry: "Managed Healthcare", description: "Health care company offering insurance and health services." },
  { ticker: "XOM", name: "Exxon Mobil Corporation", exchange: "NYSE", sector: "Energy", industry: "Oil & Gas", description: "Explores for and produces crude oil and natural gas." },
  { ticker: "JNJ", name: "Johnson & Johnson", exchange: "NYSE", sector: "Healthcare", industry: "Pharmaceuticals", description: "Develops medical devices, pharmaceuticals, and consumer health products." },
  { ticker: "WMT", name: "Walmart Inc.", exchange: "NYSE", sector: "Consumer Staples", industry: "Retail", description: "Operates retail stores, e-commerce, and wholesale clubs globally." },
  { ticker: "PG", name: "Procter & Gamble Co.", exchange: "NYSE", sector: "Consumer Staples", industry: "Household Products", description: "Manufactures branded consumer packaged goods." },
  { ticker: "HD", name: "The Home Depot Inc.", exchange: "NYSE", sector: "Consumer Discretionary", industry: "Home Improvement Retail", description: "Home improvement retailer operating stores across North America." },
  { ticker: "CVX", name: "Chevron Corporation", exchange: "NYSE", sector: "Energy", industry: "Oil & Gas", description: "Integrated energy company with upstream and downstream operations." },
  { ticker: "MRK", name: "Merck & Co. Inc.", exchange: "NYSE", sector: "Healthcare", industry: "Pharmaceuticals", description: "Global health care company delivering medicines and vaccines." },
  { ticker: "ABBV", name: "AbbVie Inc.", exchange: "NYSE", sector: "Healthcare", industry: "Biotechnology", description: "Biopharmaceutical company focused on immunology and oncology." },
  { ticker: "COST", name: "Costco Wholesale Corporation", exchange: "NASDAQ", sector: "Consumer Staples", industry: "Retail", description: "Membership warehouse club operator." },
  { ticker: "PEP", name: "PepsiCo Inc.", exchange: "NASDAQ", sector: "Consumer Staples", industry: "Beverages", description: "Food and beverage company with global snack and drink brands." },
  { ticker: "ADBE", name: "Adobe Inc.", exchange: "NASDAQ", sector: "Technology", industry: "Software", description: "Creative, document, and experience cloud software company." },
  { ticker: "CRM", name: "Salesforce Inc.", exchange: "NYSE", sector: "Technology", industry: "Software", description: "Cloud-based CRM and enterprise software provider." },
  { ticker: "NFLX", name: "Netflix Inc.", exchange: "NASDAQ", sector: "Communication Services", industry: "Entertainment", description: "Streaming entertainment service with global subscriber base." },
  { ticker: "AMD", name: "Advanced Micro Devices Inc.", exchange: "NASDAQ", sector: "Technology", industry: "Semiconductors", description: "Designs high-performance computing and graphics processors." },
  { ticker: "INTC", name: "Intel Corporation", exchange: "NASDAQ", sector: "Technology", industry: "Semiconductors", description: "Designs and manufactures semiconductor chips and platforms." },
  { ticker: "DIS", name: "The Walt Disney Company", exchange: "NYSE", sector: "Communication Services", industry: "Entertainment", description: "Media and entertainment conglomerate with parks and streaming." },
  { ticker: "BAC", name: "Bank of America Corp.", exchange: "NYSE", sector: "Financial Services", industry: "Conventional Banking", description: "Full-service banking and financial services institution." },
  { ticker: "WFC", name: "Wells Fargo & Company", exchange: "NYSE", sector: "Financial Services", industry: "Conventional Banking", description: "Diversified financial services company with banking operations." },
  { ticker: "C", name: "Citigroup Inc.", exchange: "NYSE", sector: "Financial Services", industry: "Conventional Banking", description: "Global banking and financial services corporation." },
  { ticker: "GS", name: "The Goldman Sachs Group Inc.", exchange: "NYSE", sector: "Financial Services", industry: "Investment Banking", description: "Global investment banking, securities, and investment management." },
  { ticker: "MS", name: "Morgan Stanley", exchange: "NYSE", sector: "Financial Services", industry: "Investment Banking", description: "Financial services firm providing investment banking and wealth management." },
  { ticker: "T", name: "AT&T Inc.", exchange: "NYSE", sector: "Communication Services", industry: "Telecom", description: "Telecommunications and media company." },
  { ticker: "VZ", name: "Verizon Communications Inc.", exchange: "NYSE", sector: "Communication Services", industry: "Telecom", description: "Wireless and wireline communications services provider." },
  { ticker: "CMCSA", name: "Comcast Corporation", exchange: "NASDAQ", sector: "Communication Services", industry: "Media", description: "Cable, broadband, and media entertainment company." },
  { ticker: "PFE", name: "Pfizer Inc.", exchange: "NYSE", sector: "Healthcare", industry: "Pharmaceuticals", description: "Biopharmaceutical company developing medicines and vaccines." },
  { ticker: "NKE", name: "NIKE Inc.", exchange: "NYSE", sector: "Consumer Discretionary", industry: "Apparel", description: "Designs and sells athletic footwear, apparel, and equipment." },
  { ticker: "MCD", name: "McDonald's Corporation", exchange: "NYSE", sector: "Consumer Discretionary", industry: "Restaurants", description: "Global fast-food restaurant chain operator and franchisor." },
  { ticker: "SBUX", name: "Starbucks Corporation", exchange: "NASDAQ", sector: "Consumer Discretionary", industry: "Restaurants", description: "Specialty coffee roaster and retailer." },
  { ticker: "BA", name: "The Boeing Company", exchange: "NYSE", sector: "Industrials", industry: "Aerospace", description: "Designs and manufactures commercial and defense aircraft." },
  { ticker: "CAT", name: "Caterpillar Inc.", exchange: "NYSE", sector: "Industrials", industry: "Machinery", description: "Manufactures construction and mining equipment." },
  { ticker: "GE", name: "GE Aerospace", exchange: "NYSE", sector: "Industrials", industry: "Aerospace", description: "Aerospace engines and industrial technology company." },
  { ticker: "HON", name: "Honeywell International Inc.", exchange: "NASDAQ", sector: "Industrials", industry: "Conglomerate", description: "Technology and manufacturing company across aerospace and building tech." },
  { ticker: "UPS", name: "United Parcel Service Inc.", exchange: "NYSE", sector: "Industrials", industry: "Logistics", description: "Package delivery and supply chain management company." },
  { ticker: "RTX", name: "RTX Corporation", exchange: "NYSE", sector: "Industrials", industry: "Aerospace & Defense", description: "Aerospace and defense technology company." },
  { ticker: "LMT", name: "Lockheed Martin Corporation", exchange: "NYSE", sector: "Industrials", industry: "Aerospace & Defense", description: "Global security and aerospace company." },
  { ticker: "NEE", name: "NextEra Energy Inc.", exchange: "NYSE", sector: "Utilities", industry: "Electric Utilities", description: "Electric utility and renewable energy company." },
  { ticker: "DUK", name: "Duke Energy Corporation", exchange: "NYSE", sector: "Utilities", industry: "Electric Utilities", description: "Regulated electric and gas utility holding company." },
  { ticker: "SO", name: "The Southern Company", exchange: "NYSE", sector: "Utilities", industry: "Electric Utilities", description: "Electric utility holding company in the southeastern US." },
  { ticker: "PLD", name: "Prologis Inc.", exchange: "NYSE", sector: "Real Estate", industry: "REIT", description: "Global logistics real estate investment trust." },
  { ticker: "AMT", name: "American Tower Corporation", exchange: "NYSE", sector: "Real Estate", industry: "REIT", description: "Wireless and broadcast communications infrastructure REIT." },
  { ticker: "LIN", name: "Linde plc", exchange: "NASDAQ", sector: "Materials", industry: "Industrial Gases", description: "Industrial gas and engineering company." },
  { ticker: "FCX", name: "Freeport-McMoRan Inc.", exchange: "NYSE", sector: "Materials", industry: "Mining", description: "Copper, gold, and molybdenum mining company." },
  { ticker: "NEM", name: "Newmont Corporation", exchange: "NYSE", sector: "Materials", industry: "Gold Mining", description: "Gold and copper mining company." },
  { ticker: "TMUS", name: "T-Mobile US Inc.", exchange: "NASDAQ", sector: "Communication Services", industry: "Telecom", description: "Wireless communications services provider." },
  { ticker: "ORCL", name: "Oracle Corporation", exchange: "NYSE", sector: "Technology", industry: "Software", description: "Enterprise software, cloud infrastructure, and database company." },
  { ticker: "IBM", name: "International Business Machines Corp.", exchange: "NYSE", sector: "Technology", industry: "IT Services", description: "Hybrid cloud, AI, and enterprise technology services." },
  { ticker: "QCOM", name: "QUALCOMM Inc.", exchange: "NASDAQ", sector: "Technology", industry: "Semiconductors", description: "Wireless technology and semiconductor company." },
  { ticker: "AVGO", name: "Broadcom Inc.", exchange: "NASDAQ", sector: "Technology", industry: "Semiconductors", description: "Designs and supplies semiconductor and infrastructure software." },
  { ticker: "TXN", name: "Texas Instruments Inc.", exchange: "NASDAQ", sector: "Technology", industry: "Semiconductors", description: "Designs and manufactures analog and embedded processing chips." },
  { ticker: "NOW", name: "ServiceNow Inc.", exchange: "NYSE", sector: "Technology", industry: "Software", description: "Cloud-based workflow and digital transformation platform." },
  { ticker: "INTU", name: "Intuit Inc.", exchange: "NASDAQ", sector: "Technology", industry: "Software", description: "Financial software including TurboTax and QuickBooks." },
  { ticker: "ISRG", name: "Intuitive Surgical Inc.", exchange: "NASDAQ", sector: "Healthcare", industry: "Medical Devices", description: "Robotic-assisted surgical systems manufacturer." },
  { ticker: "GILD", name: "Gilead Sciences Inc.", exchange: "NASDAQ", sector: "Healthcare", industry: "Biotechnology", description: "Biopharmaceutical company focused on antiviral therapies." },
  { ticker: "BMY", name: "Bristol-Myers Squibb Co.", exchange: "NYSE", sector: "Healthcare", industry: "Pharmaceuticals", description: "Biopharmaceutical company in oncology and immunology." },
  { ticker: "TMO", name: "Thermo Fisher Scientific Inc.", exchange: "NYSE", sector: "Healthcare", industry: "Life Sciences Tools", description: "Life sciences solutions and laboratory equipment provider." },
  { ticker: "LOW", name: "Lowe's Companies Inc.", exchange: "NYSE", sector: "Consumer Discretionary", industry: "Home Improvement Retail", description: "Home improvement retailer in the US." },
  { ticker: "TGT", name: "Target Corporation", exchange: "NYSE", sector: "Consumer Discretionary", industry: "Retail", description: "General merchandise and food discount retailer." },
  { ticker: "F", name: "Ford Motor Company", exchange: "NYSE", sector: "Automotive", industry: "Automobiles", description: "Designs, manufactures, and sells Ford and Lincoln vehicles." },
  { ticker: "GM", name: "General Motors Company", exchange: "NYSE", sector: "Automotive", industry: "Automobiles", description: "Designs, builds, and sells cars, trucks, and automotive parts." },
  { ticker: "RIVN", name: "Rivian Automotive Inc.", exchange: "NASDAQ", sector: "Automotive", industry: "Electric Vehicles", description: "Electric vehicle manufacturer focused on trucks and SUVs." },
  { ticker: "LCID", name: "Lucid Group Inc.", exchange: "NASDAQ", sector: "Automotive", industry: "Electric Vehicles", description: "Luxury electric vehicle manufacturer." },
  { ticker: "MO", name: "Altria Group Inc.", exchange: "NYSE", sector: "Consumer Staples", industry: "Tobacco", description: "Tobacco products manufacturer — prohibited under most Shariah screens." },
  { ticker: "PM", name: "Philip Morris International Inc.", exchange: "NYSE", sector: "Consumer Staples", industry: "Tobacco", description: "Tobacco and smoke-free product company." },
  { ticker: "BUD", name: "Anheuser-Busch InBev SA/NV", exchange: "NYSE", sector: "Consumer Staples", industry: "Brewery", description: "Global brewer of beer and alcoholic beverages." },
  { ticker: "STZ", name: "Constellation Brands Inc.", exchange: "NYSE", sector: "Consumer Staples", industry: "Alcohol", description: "Producer and marketer of beer, wine, and spirits." },
  { ticker: "LVS", name: "Las Vegas Sands Corp.", exchange: "NYSE", sector: "Consumer Discretionary", industry: "Casino", description: "Resort and casino operator in Macao and Singapore." },
  { ticker: "MGM", name: "MGM Resorts International", exchange: "NYSE", sector: "Consumer Discretionary", industry: "Casino", description: "Hotel, entertainment, and gaming company." },
  { ticker: "SPOT", name: "Spotify Technology S.A.", exchange: "NYSE", sector: "Communication Services", industry: "Music Streaming", description: "Audio streaming and media services platform." },
  { ticker: "SNAP", name: "Snap Inc.", exchange: "NYSE", sector: "Communication Services", industry: "Social Media", description: "Camera and messaging social media platform." },
  { ticker: "UBER", name: "Uber Technologies Inc.", exchange: "NYSE", sector: "Technology", industry: "Ride-Sharing", description: "Mobility and delivery technology platform." },
  { ticker: "ABNB", name: "Airbnb Inc.", exchange: "NASDAQ", sector: "Consumer Discretionary", industry: "Travel", description: "Online marketplace for lodging and experiences." },
  { ticker: "SQ", name: "Block Inc.", exchange: "NYSE", sector: "Technology", industry: "Fintech", description: "Financial services and digital payments company (Square/Cash App)." },
  { ticker: "PYPL", name: "PayPal Holdings Inc.", exchange: "NASDAQ", sector: "Financial Services", industry: "Payment Processing", description: "Digital payments platform enabling online money transfers." },
  { ticker: "COIN", name: "Coinbase Global Inc.", exchange: "NASDAQ", sector: "Financial Services", industry: "Crypto Exchange", description: "Cryptocurrency exchange and financial services platform." },
  { ticker: "SCHW", name: "The Charles Schwab Corporation", exchange: "NYSE", sector: "Financial Services", industry: "Brokerage", description: "Brokerage and banking services for investors." },
  { ticker: "BLK", name: "BlackRock Inc.", exchange: "NYSE", sector: "Financial Services", industry: "Asset Management", description: "Global investment management and technology provider." },
  { ticker: "SPGI", name: "S&P Global Inc.", exchange: "NYSE", sector: "Financial Services", industry: "Financial Data", description: "Financial information, ratings, and analytics provider." },
  { ticker: "DE", name: "Deere & Company", exchange: "NYSE", sector: "Industrials", industry: "Agricultural Machinery", description: "Manufactures agricultural, construction, and forestry equipment." },
  { ticker: "MMM", name: "3M Company", exchange: "NYSE", sector: "Industrials", industry: "Conglomerate", description: "Industrial, safety, and consumer products manufacturer." },
  { ticker: "EMR", name: "Emerson Electric Co.", exchange: "NYSE", sector: "Industrials", industry: "Industrial Automation", description: "Automation solutions and commercial/residential solutions provider." },
  { ticker: "SLB", name: "Schlumberger Limited", exchange: "NYSE", sector: "Energy", industry: "Oilfield Services", description: "Oilfield services and equipment company." },
  { ticker: "COP", name: "ConocoPhillips", exchange: "NYSE", sector: "Energy", industry: "Oil & Gas", description: "Independent exploration and production company." },
  { ticker: "EOG", name: "EOG Resources Inc.", exchange: "NYSE", sector: "Energy", industry: "Oil & Gas", description: "Crude oil and natural gas exploration company." },
  { ticker: "MDLZ", name: "Mondelez International Inc.", exchange: "NASDAQ", sector: "Consumer Staples", industry: "Food Products", description: "Global snack food and confectionery company." },
  { ticker: "CL", name: "Colgate-Palmolive Company", exchange: "NYSE", sector: "Consumer Staples", industry: "Household Products", description: "Household and personal care products manufacturer." },
  { ticker: "EL", name: "The Estée Lauder Companies Inc.", exchange: "NYSE", sector: "Consumer Staples", industry: "Personal Products", description: "Prestige beauty and skincare products company." },
  { ticker: "SHOP", name: "Shopify Inc.", exchange: "NYSE", sector: "Technology", industry: "E-Commerce Software", description: "Commerce platform for online stores and retail point-of-sale." },
  { ticker: "PANW", name: "Palo Alto Networks Inc.", exchange: "NASDAQ", sector: "Technology", industry: "Cybersecurity", description: "Cybersecurity platform and services provider." },
  { ticker: "CRWD", name: "CrowdStrike Holdings Inc.", exchange: "NASDAQ", sector: "Technology", industry: "Cybersecurity", description: "Cloud-delivered endpoint and workload protection platform." },
  { ticker: "SNOW", name: "Snowflake Inc.", exchange: "NYSE", sector: "Technology", industry: "Cloud Software", description: "Cloud-based data platform for analytics and AI." },
  { ticker: "PLTR", name: "Palantir Technologies Inc.", exchange: "NYSE", sector: "Technology", industry: "Software", description: "Data analytics and AI platform for government and enterprise." },
  { ticker: "ARM", name: "Arm Holdings plc", exchange: "NASDAQ", sector: "Technology", industry: "Semiconductors", description: "Semiconductor intellectual property and chip architecture designer." },
  { ticker: "SMCI", name: "Super Micro Computer Inc.", exchange: "NASDAQ", sector: "Technology", industry: "Computer Hardware", description: "High-performance server and storage solutions provider." },
];
