import type { CompanyRecord } from "@/lib/stocks/types";

/** Manually reviewed flagship companies with rich screening overrides */
export const DETAILED_COMPANIES: CompanyRecord[] = [
  {
    ticker: "AAPL",
    name: "Apple Inc.",
    exchange: "NASDAQ",
    sector: "Technology",
    industry: "Consumer Electronics",
    description:
      "Designs and manufactures smartphones, computers, wearables, and digital services including the App Store and Apple Music.",
    marketCapValue: 3200,
    interestBearingDebt: 907,
    impureIncomeRatio: 2.8,
    overrides: {
      businessStatus: "questionable",
      businessSummary:
        "Core hardware and software revenue is permissible; financial services partnership raises concerns.",
      businessDetails: [
        "Primary revenue from iPhone, Mac, iPad, and services",
        "Apple Card partnership involves interest-based financial products",
        "App Store hosts mixed content — minor non-compliant revenue",
        "No direct involvement in alcohol, gambling, or pork industries",
      ],
      revenueBreakdown: [
        { label: "Hardware (iPhone, Mac, iPad)", percentage: 52, compliant: true },
        { label: "Services (App Store, iCloud)", percentage: 24, compliant: true },
        { label: "Wearables & Accessories", percentage: 10, compliant: true },
        { label: "Financial Services (Apple Card)", percentage: 3, compliant: false },
        { label: "Other", percentage: 11, compliant: true },
      ],
      prohibitedExposure: 3,
      sectorStatus: "halal",
      sectorSummary: "Technology sector is generally permissible under Shariah principles.",
      sectorFlags: ["Minor financial services exposure"],
      riskLevel: "low",
      reasoning: [
        "Apple's core business of consumer electronics and software is Shariah-compliant.",
        "Debt ratio of ~28.4% is within the 33% AAOIFI threshold.",
        "Apple Card/Goldman Sachs partnership introduces interest-based revenue (~3%).",
        "Mixed scholarly opinions — some classify as halal, others as questionable.",
        "Recommend consulting a qualified Islamic finance scholar for personal guidance.",
      ],
    },
  },
  {
    ticker: "TSLA",
    name: "Tesla, Inc.",
    exchange: "NASDAQ",
    sector: "Automotive",
    industry: "Electric Vehicles",
    description:
      "Designs, manufactures, and sells electric vehicles, energy storage systems, and solar energy products.",
    marketCapValue: 800,
    interestBearingDebt: 42,
    impureIncomeRatio: 0.5,
    overrides: {
      businessStatus: "halal",
      businessSummary:
        "Electric vehicle manufacturing and clean energy — fully permissible business activities.",
      businessDetails: [
        "Revenue primarily from electric vehicle sales",
        "Energy storage and solar products are permissible",
        "No involvement in prohibited industries",
        "Minimal non-compliant revenue exposure",
      ],
      revenueBreakdown: [
        { label: "Automotive Sales", percentage: 82, compliant: true },
        { label: "Energy Generation & Storage", percentage: 8, compliant: true },
        { label: "Services & Other", percentage: 10, compliant: true },
      ],
      prohibitedExposure: 0.5,
      sectorStatus: "halal",
      sectorSummary: "Automotive manufacturing is a permissible industry in Islamic finance.",
      sectorFlags: [],
      riskLevel: "low",
      reasoning: [
        "Tesla's core business of EV manufacturing is Shariah-compliant.",
        "Extremely low debt ratio of ~5.2% — well within Shariah limits.",
        "Non-compliant revenue below 1% — negligible purification requirement.",
        "Widely accepted as halal by major Islamic finance screening providers.",
      ],
    },
  },
  {
    ticker: "NVDA",
    name: "NVIDIA Corporation",
    exchange: "NASDAQ",
    sector: "Technology",
    industry: "Semiconductors",
    description:
      "Designs GPUs and AI computing platforms for gaming, data centers, autonomous vehicles, and professional visualization.",
    marketCapValue: 3100,
    interestBearingDebt: 397,
    impureIncomeRatio: 1.2,
    overrides: {
      businessStatus: "halal",
      businessSummary: "Semiconductor design and AI computing — core business is Shariah-compliant.",
      businessDetails: [
        "Designs graphics processing units and AI chips",
        "Serves gaming, cloud, and enterprise markets",
        "Some indirect defense/AI applications noted by scholars",
        "No direct prohibited industry involvement",
      ],
      revenueBreakdown: [
        { label: "Data Center / AI", percentage: 55, compliant: true },
        { label: "Gaming", percentage: 25, compliant: true },
        { label: "Professional Visualization", percentage: 8, compliant: true },
        { label: "Automotive", percentage: 7, compliant: true },
        { label: "Other", percentage: 5, compliant: true },
      ],
      prohibitedExposure: 1.2,
      sectorStatus: "halal",
      sectorSummary: "Semiconductor industry is permissible; technology sector passes screening.",
      sectorFlags: ["Indirect defense AI applications"],
      riskLevel: "low",
      reasoning: [
        "NVIDIA's chip design business is fundamentally Shariah-compliant.",
        "Debt ratio of ~12.8% is comfortably within the 33% threshold.",
        "Impure income exposure below 2% — within purification limits.",
        "Generally classified as halal by Islamic finance screeners.",
      ],
    },
  },
  {
    ticker: "MSFT",
    name: "Microsoft Corporation",
    exchange: "NASDAQ",
    sector: "Technology",
    industry: "Software & Cloud",
    description:
      "Develops software, cloud services (Azure), productivity tools (Office 365), and gaming (Xbox) platforms.",
    marketCapValue: 3100,
    interestBearingDebt: 580,
    impureIncomeRatio: 1.5,
    overrides: {
      businessStatus: "halal",
      businessSummary:
        "Software and cloud services are permissible; gaming content requires minor screening.",
      businessDetails: [
        "Azure cloud and Office 365 are core revenue drivers",
        "LinkedIn and enterprise software are compliant",
        "Xbox gaming may include mature-rated content (minor revenue)",
        "No conventional banking or prohibited industry involvement",
      ],
      revenueBreakdown: [
        { label: "Cloud & Server Products (Azure)", percentage: 42, compliant: true },
        { label: "Office & Productivity", percentage: 24, compliant: true },
        { label: "Windows & Devices", percentage: 14, compliant: true },
        { label: "Gaming (Xbox)", percentage: 12, compliant: true },
        { label: "LinkedIn & Other", percentage: 8, compliant: true },
      ],
      prohibitedExposure: 1.5,
      sectorStatus: "halal",
      sectorSummary: "Technology and software sector passes Shariah sector screening.",
      sectorFlags: [],
      riskLevel: "low",
      reasoning: [
        "Microsoft's core cloud and software business is Shariah-compliant.",
        "Debt ratio of ~18.7% is well within acceptable limits.",
        "Non-compliant revenue exposure is minimal (~1.5%).",
        "Classified as halal by most major Islamic finance providers.",
      ],
    },
  },
  {
    ticker: "AMZN",
    name: "Amazon.com, Inc.",
    exchange: "NASDAQ",
    sector: "Consumer Discretionary",
    industry: "E-Commerce & Cloud",
    description:
      "Operates the world's largest e-commerce marketplace and Amazon Web Services (AWS) cloud computing platform.",
    marketCapValue: 1900,
    interestBearingDebt: 585,
    impureIncomeRatio: 2.1,
    overrides: {
      businessStatus: "halal",
      businessSummary:
        "E-commerce and cloud computing are permissible; marketplace hosts third-party mixed products.",
      businessDetails: [
        "AWS cloud services are the primary profit driver",
        "E-commerce marketplace is fundamentally permissible",
        "Third-party sellers may offer non-halal products (marketplace model)",
        "Amazon Prime Video includes mixed content (minor revenue)",
      ],
      revenueBreakdown: [
        { label: "Online Stores", percentage: 38, compliant: true },
        { label: "AWS Cloud Services", percentage: 32, compliant: true },
        { label: "Third-Party Seller Services", percentage: 18, compliant: true },
        { label: "Advertising", percentage: 8, compliant: true },
        { label: "Prime & Other", percentage: 4, compliant: false },
      ],
      prohibitedExposure: 2.1,
      sectorStatus: "halal",
      sectorSummary: "E-commerce and cloud computing sectors are permissible.",
      sectorFlags: ["Marketplace third-party product screening"],
      riskLevel: "low",
      reasoning: [
        "Amazon's core e-commerce and AWS cloud business is Shariah-compliant.",
        "Debt ratio of ~30.8% is within the 33% threshold but approaching the limit.",
        "Minor non-compliant revenue (~2.1%) is within purification thresholds.",
        "Generally accepted as halal by Islamic finance screeners.",
      ],
    },
  },
  {
    ticker: "META",
    name: "Meta Platforms, Inc.",
    exchange: "NASDAQ",
    sector: "Technology",
    industry: "Social Media & Advertising",
    description:
      "Operates Facebook, Instagram, WhatsApp, and invests in metaverse/VR technologies through Reality Labs.",
    marketCapValue: 1400,
    interestBearingDebt: 288,
    impureIncomeRatio: 3.5,
    overrides: {
      businessStatus: "questionable",
      businessSummary:
        "Social media advertising is permissible; content moderation and metaverse losses raise questions.",
      businessDetails: [
        "Primary revenue from digital advertising on social platforms",
        "Platform may host non-compliant content (advertising model)",
        "Reality Labs/metaverse investments are permissible activities",
        "No direct prohibited industry involvement",
      ],
      revenueBreakdown: [
        { label: "Advertising (Facebook, Instagram)", percentage: 88, compliant: true },
        { label: "Reality Labs (VR/Metaverse)", percentage: 2, compliant: true },
        { label: "Mixed Platform Content Revenue", percentage: 3.5, compliant: false },
        { label: "Other Services", percentage: 6.5, compliant: true },
      ],
      prohibitedExposure: 3.5,
      sectorStatus: "questionable",
      sectorSummary: "Social media sector has mixed scholarly opinions on content-based revenue.",
      sectorFlags: ["User-generated content concerns", "Advertising on mixed content"],
      riskLevel: "medium",
      reasoning: [
        "Meta's advertising business model is generally permissible.",
        "Debt ratio of ~20.6% is within Shariah limits.",
        "Platform content moderation creates ~3.5% non-compliant revenue exposure.",
        "Some scholars classify as halal; others flag as questionable due to content.",
      ],
    },
  },
  {
    ticker: "JPM",
    name: "JPMorgan Chase & Co.",
    exchange: "NYSE",
    sector: "Financial Services",
    industry: "Conventional Banking",
    description:
      "Global financial services firm offering investment banking, commercial banking, asset management, and consumer banking.",
    marketCapValue: 580,
    interestBearingDebt: 519,
    impureIncomeRatio: 85,
    overrides: {
      businessStatus: "haram",
      businessSummary:
        "Conventional interest-based banking — core business model is prohibited under Shariah.",
      businessDetails: [
        "Primary revenue from interest-based lending (riba)",
        "Investment banking with conventional finance products",
        "Consumer banking with interest-bearing accounts and loans",
        "Revenue overwhelmingly from prohibited financial activities",
      ],
      revenueBreakdown: [
        { label: "Net Interest Income (Riba)", percentage: 52, compliant: false },
        { label: "Investment Banking", percentage: 22, compliant: false },
        { label: "Asset & Wealth Management", percentage: 15, compliant: false },
        { label: "Other Financial Services", percentage: 11, compliant: false },
      ],
      prohibitedExposure: 85,
      sectorStatus: "haram",
      sectorSummary: "Conventional banking is explicitly prohibited under Islamic finance principles.",
      sectorFlags: [
        "Interest-based lending (Riba)",
        "Conventional insurance products",
        "Derivatives and interest-based instruments",
      ],
      riskLevel: "high",
      reasoning: [
        "JPMorgan's core business is interest-based banking (riba) — explicitly haram.",
        "Debt ratio of ~89.5% far exceeds any acceptable Shariah threshold.",
        "Over 85% of revenue from non-compliant financial activities.",
        "Unanimously classified as haram by all major Islamic finance authorities.",
      ],
    },
  },
  {
    ticker: "KO",
    name: "The Coca-Cola Company",
    exchange: "NYSE",
    sector: "Consumer Staples",
    industry: "Beverages",
    description:
      "Manufactures, markets, and sells non-alcoholic beverages including Coca-Cola, Sprite, and Fanta globally.",
    marketCapValue: 260,
    interestBearingDebt: 81,
    impureIncomeRatio: 4.2,
    overrides: {
      businessStatus: "questionable",
      businessSummary:
        "Beverage company with majority halal products; minor alcoholic beverage revenue.",
      businessDetails: [
        "Primary revenue from non-alcoholic soft drinks",
        "Some international products contain alcohol (minor revenue)",
        "Bottling partnerships in mixed markets",
        "No gambling, banking, or pork industry involvement",
      ],
      revenueBreakdown: [
        { label: "Non-Alcoholic Beverages", percentage: 88, compliant: true },
        { label: "Alcoholic Beverages (International)", percentage: 4, compliant: false },
        { label: "Bottling & Distribution", percentage: 5, compliant: true },
        { label: "Other", percentage: 3, compliant: true },
      ],
      prohibitedExposure: 4.2,
      sectorStatus: "questionable",
      sectorSummary: "Beverage sector with mixed product portfolio — scholarly opinions vary.",
      sectorFlags: ["Minor alcohol revenue (~4%)", "Debt ratio near threshold"],
      riskLevel: "medium",
      reasoning: [
        "Majority of revenue (~88%) from non-alcoholic beverages.",
        "Small alcohol revenue (~4%) raises Shariah concerns for some scholars.",
        "Debt ratio of ~31.2% is close to the 33% AAOIFI limit.",
        "Classified as questionable — consult a scholar for personal guidance.",
      ],
    },
  },
];
